### ISSUE TITLE
No support for Polygon Amoy Testnet

### ISSUE THREAD

**Issue by AB7zz** [Web3Auth/web3auth-web#1763]
I'm not able to connect to Polygon Amoy testnet.

I'd like it if web3auth quickly supported transactions on amoy testnet. If it does exist then I'd like it if the config for each chain was mentioned somewhere in the docs.

**Comment by antoinefarley** [comment]
We're also dealing with transactions failing because of inconsistent and extreme transaction fees on OpenLogin (25 MATIC for a contract write). The same config and code works with the MetaMask connector. We are still on Cyan network. Changing the SAPPHIRE network results in some transactions passing but still unusable. 

To be clear, the same code works perfectly on Polygon Mumbai or Ethereum Sepolia.

**Comment by chaitanyapotti** [comment]
Polygon Amoy is fully supported.
