### ISSUE TITLE
ADAPTER_EVENTS.ERRORED event not triggered in Openlogin Adapter on 'session likely expired' error.

### ISSUE THREAD

**Issue by kubrysh** [Web3Auth/web3auth-web#290]
### **Describe the bug**

In case of cached Openlogin Adapter presence, `Web3Auth` Instance tries to auto connect on initialization. But if the session is expired – `ADAPTER_EVENTS.ERRORED` event is not triggered, only an error is logged in the console.

### **Expected behavior**

For `ADAPTER_EVENTS.ERRORED` to get triggered on `session likely expired` error in Openlogin Adapter.

- Web3Auth Version: 1.1.1

**Comment by denny999222** [comment]
Same issue here. Difficult to manage user sessions without this

**Comment by chaitanyapotti** [comment]
This is by design. We have session mgmt built in. So, while calling init() if session is already available, you will be logged in and connected event will be fired.
On the other hand, if session is expired, the adapter moves to ready state... so that you can call connect again. This is not an error.

Sessions typically last for 1-7 days depending on `sessionTime` configuration.
